# import pyfiglet module 
import pyfiglet
import os,sys,time
os.system('clear')

Y = "\033[33;1m" #Red
G ="\033[32m" #Green
B = "\033[34m" #Blue
W ="\033[0m" #White
C ="\003[36;1m" #Cyan
R = "\033[31m" #Red

def load(word):
	for char in word:
		print(char,end="")
		sys.stdout.flush()
		time.sleep(0.01)
		
banner = pyfiglet.figlet_format("PRO HACKER") 

name = ("[+]-------------BY AMEER 404 FROM TEAM 404------------[+]")
line = ("---------------------------------------------------------")

ban2 = pyfiglet.figlet_format("HACK NASA")

empty = (" ")

load(f"{G}"+banner+"\n")
load(f"{B}"+line+"\n")
load(f"{R}"+name+"\n")
load(f"{B}"+line+"\n")
load(f"{Y}"+empty+"\n")

input("           Do You Want Continue[Press Eny Key]: ")
os.system("pkg install pyfiglet")


os.system('clear')


empty = (" ")

load(f"{B}"+banner+"\n")
load(f"{Y}"+line+"\n")
load(f"{R}"+name+"\n")
load(f"{Y}"+line+"\n")
load(f"{G}"+empty+"\n")

print(empty)
print(" [01] HACK NASA")
print(" [02] HACK FBI")
print(" [03] HACK CIA")
print(" [04] HACK GOOGLE")
print(empty)
inp=int(input(" [#] Enter Choice: "))
if inp ==1:
	load(f"{Y}"+empty+"\n")
	time.sleep(0)
	os.system("clear")
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	time.sleep(3)
	load(f"{G}"+ban2+"\n")
	load(f"{Y}"+line+"\n")
	load(f"{R}"+name+"\n")
	load(f"{Y}"+line+"\n")
	load(f"{G}"+empty+"\n")
	time.sleep(2)
	load(f"{B}"+"Getting Pakeges"+'\n')
	time.sleep(2)
	load(f"{B}"+"Pakege Updating"+'\n')
	time.sleep(3)
	os.system('clear')
	load(f"{Y}"+ empty+"\n")
	print("പോയിവല്ലവാഴയും വെക്ക് പുള്ളെ")
	print(empty)
	print("End")
	
elif inp ==2:
	load(f"{Y}"+empty+"\n")
	time.sleep(0)
	os.system("clear")
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... \ ")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... /")
	time.sleep(1)
	os.system('clear')
	print(" Tool Starting... -")
	time.sleep(1)
	os.system('clear')
	time.sleep(3)
	os.system('clear')
	load(f"{Y}"+ empty+"\n")
	print("പോയിവല്ല പണിയെടുത്ത് ജീവിക്ക് പുള്ളേ")
	load(f"{G}"+empty+"\n")
	print("End")

elif inp ==3:
	os.system("clear")
	time.sleep(5)
	print("Getting Data")
	time.sleep(3)
	print("Installing")
	time.sleep(3)
	os.system("clear")
	print (" പോയി വാഴക്ക് തടം എടുക്ക് പുള്ളേ")
	load(f"{B}"+empty+"\n")
	print("End")
	
elif inp ==4:
	os.system('clear')
	time.sleep(6)
	load(f"{B}"+empty+"\n")
	print(" ഒന്ന് പോയ ചാവെടെക്")
	